### ISSUE TITLE
Is there any plans to publish latest MS WebDriver NuGet package?

### ISSUE THREAD

**Issue by jsakamoto** [cchitsiang/nuget-selenium-webdriver-microsoftwebdriver#10]
Thank you for accept the pull request which I sent.

- Pull request #9 

But, at this time, the NuGet package of MS WebDriver latest version doesn't publish yet.

Is there any plans to publish latest MS WebDriver NuGet package in these days? 

P.S.  
If you need to new package files, there is an package file which I built 4 days before on my forked repository.

https://github.com/jsakamoto/nuget-selenium-webdriver-microsoftwebdriver/releases/tag/v.10.0.16299

**Comment by rafflesgun** [comment]
@jsakamoto, latest NuGet package had published.

**Comment by jsakamoto** [comment]
@rafflesgun Thank you very much for your great work! 👍
