### ISSUE TITLE
Update WebDriver to  17134 

### ISSUE THREAD

**Issue by SteveBush** [cchitsiang/nuget-selenium-webdriver-microsoftwebdriver#11]
Can you update your nuget package to the latest version of the Microsoft Web Driver.

Release 17134 Version: 6.17134 | Edge version supported: 17.17134 | License terms
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by cchitsiang** [comment]
Sure, will try to get @rafflesgun look into it. Thanks for head up

**Comment by rafflesgun** [comment]
@SteveBush package updated.
