### ISSUE TITLE
MS WebDriver newer version Release 14393 is now available.

### ISSUE THREAD

**Issue by jsakamoto** [cchitsiang/nuget-selenium-webdriver-microsoftwebdriver#3]
The newer version of Microsoft WebDriver "Release 14393" is now available.

https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

But the WebDriver that is contained in this NuGet package is previous version (Release 10586). 

Could you upgrade the MS WebDriver binary in this NuGet package?

**Comment by cchitsiang** [comment]
Yes, shouldn't have any problem. Will do that shortly

**Comment by cchitsiang** [comment]
Updated on Nuget: https://www.nuget.org/packages/Selenium.WebDriver.MicrosoftWebDriver/10.0.14393

**Comment by jsakamoto** [comment]
Thanks! 👍
