### ISSUE TITLE
Update-Package command at Package Manager Console installed incorrect version of this package.

### ISSUE THREAD

**Issue by jsakamoto** [cchitsiang/nuget-selenium-webdriver-microsoftwebdriver#7]
I reported it to Microsoft.

https://developercommunity.visualstudio.com/content/problem/46121/update-package-command-at-package-manager-console.html

Please vote that report if you prefer.

**Comment by cchitsiang** [comment]
Voted!

**Comment by cchitsiang** [comment]
Close it as outdated
