### ISSUE TITLE
mslso.dll missing

### ISSUE THREAD

**Issue by martinRocks** [cchitsiang/nuget-selenium-webdriver-microsoftwebdriver#8]
I'm using vs2013 on windows 10 v1607.  When I upgraded to v 10.0.15063 from 10.0.14393.1, I get an error message saying "the program can't start because mslso.dll is missing from your computer".  Version 10.0.14393.1 works just fine.

It happens when I call ...
IWebDriver Driver= new EdgeDriver();

What am I missing?

**Comment by vskh** [comment]
I experience the same issue. However, I've tried downloading MicrosoftWebDriver.exe directly from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ with the same result, so it might be a problem with webdriver itself, not with NuGet package.

**Comment by vskh** [comment]
As usual, right after posting a comment, I found possible cause myself.
It appears that the latest driver might not work as it is targeted to Edge 15063 which comes with Win 10 Creators Update. I still have older one, 14393. The dll in question probably comes with this update.
